DROP TABLE admins CASCADE CONSTRAINTS;
DROP TABLE avaliacoes CASCADE CONSTRAINTS;
DROP TABLE clinica_enderecos CASCADE CONSTRAINTS;
DROP TABLE clinica_telefones CASCADE CONSTRAINTS;
DROP TABLE clinicas CASCADE CONSTRAINTS;
DROP TABLE consultas CASCADE CONSTRAINTS;
DROP TABLE dados_biometricos_usuario CASCADE CONSTRAINTS;
DROP TABLE exame_por_consulta CASCADE CONSTRAINTS;
DROP TABLE exames CASCADE CONSTRAINTS;
DROP TABLE medico_por_clinica CASCADE CONSTRAINTS;
DROP TABLE medicos CASCADE CONSTRAINTS;
DROP TABLE tecnologias CASCADE CONSTRAINTS;
DROP TABLE usuario_enderecos CASCADE CONSTRAINTS;
DROP TABLE usuario_telefones CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;

